version: "3"
services:

  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce:latest
    restart: on-failure
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://192.168.31.227'
    ports:
      - '80:80'
      - '443:443'
      - '2020:22'
    volumes:
      - './gitlab:/etc/gitlab'          #add some configuration files about gitlab
      - '/srv/gitlab/logs:/var/log/gitlab'
      - '/srv/gitlab/data:/var/opt/gitlab'
    depends_on:
      - openldap
  
  svn:
    container_name: svn
    image: garethflowers/svn-server:latest
    restart: on-failure
    ports:
      - '3690:3690'
    volumes:
      - '../svn:/var/opt/svn'           #add some existing repos 
    depends_on:
      - openldap

  samba:
    container_name: samba
    image: dperson/samba:latest
    restart: on-failure
    ports:
      - '139:139'
      - '445:445'
    volumes:
      - './samba:/etc/samba'            #add some configuration files of samba
      - '/root/wenz/samba/share:/share'       #create a shared volume that can be managed in host machine,only read
      - '/root/wenz/samba/public:/public'     #this directory can be read&write  
      - '/root/wenz/samba/personal:/personal' #this directory need authentication      
    depends_on:
      - openldap

  openldap:
    container_name: openldap
    image: osixia/openldap:latest
    environment:
      LDAP_DOMAIN: "wenz.org"
      LDAP_ADMIN_PASSWORD: "ldap1111"   #set the password of the ldap admin user
    restart: on-failure
    volumes:
      - './ldap/ldap:/var/lib/ldap'
      - './ldap/slapd.d:/etc/ldap/slapd.d'
    domainname: "wenz.org"
    hostname: "wenz.org"
   
  phpldap:
    container_name: phpldap
    image: osixia/phpldapadmin:latest
    restart: on-failure
    environment:
        PHPLDAPADMIN_LDAP_HOSTS: "openldap"
        PHPLDAPADMIN_HTTPS: "false"
    ports:
        - '8080:80'
    depends_on:
      - openldap
