version: "3"
services:

  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce:latest
    restart: on-failure
    ports:
      - '80:80'
      - '443:443'
      - '2020:22'
    volumes:
      - './gitlab:/etc/gitlab'
      - '/srv/gitlab/logs:/var/log/gitlab'
      - '/srv/gitlab/data:/var/opt/gitlab'
    depends_on:
      - openldap
  
  svn:
    container_name: svn
    image: garethflowers/svn-server:latest
    restart: on-failure
    ports:
      - '3690:3690'
    volumes:
      - './svn:/var/opt/svn'           #add some existing repos
    depends_on:
      - openldap

  samba:
    container_name: samba
    image: dperson/samba:latest
    restart: on-failure
    ports:
      - '139:139'
      - '445:445'
    volumes:
      - '/root/wenz/samba:/share'      #create a shared volume that can be managed in host machine
      - './samba:/etc/samba'           #add the configuuation file of samba
    depends_on:
      - openldap

  openldap:
    container_name: openldap
    image: osixia/openldap:latest
    environment:
      LDAP_DOMAIN: "wenz.org"
      LDAP_ADMIN_PASSWORD: "ldap1111"  #set the password of the ldap admin user
    restart: on-failure
    domainname: "wenz.org"
    hostname: "wenz.org"
   
  phpldap:
    container_name: phpldap
    image: osixia/phpldapadmin:latest
    restart: on-failure
    environment:
        PHPLDAPADMIN_LDAP_HOSTS: "openldap"
        PHPLDAPADMIN_HTTPS: "false"
    ports:
        - '8080:80'
    depends_on:
      - openldap
